# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execucao Manual'

# regras de disparo/gatilhos/triggers
# gatilho de exec manual = workflow_dispatch
on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # maquina onde o job vai executar
    runs-on: ubuntu-latest
    # passos do script
    steps:
      # clone do projeto
      - uses: actions/checkout@v4
      # instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      # instalacao do yarn
      - name: Instalando Yarn
        run: npm install -g yarn
      # instacao dependencias
      - name: Instalando dependencias
        run: yarn
      # instalacao do playwright
      - name: Instalando Playwright
        run: yarn playwright install
      # execucao dos testes
      - name: Executando Testes E2E
        run: yarn run e2e
